version : '3'

services:
  discord-db:
    container_name: discord-db
    image: postgres:latest
    environment:
      POSTGRES_DB: discord-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    networks:
      - app-network

  discapp:
    image: edusoares/discapp:v2.0
    container_name: discapp
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: discord-db
      DB_PORT: 5432
      DB_NAME: discord-db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discord-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge