name: Deploy no ambiente de desenvolvimento.

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Build project
        run: mvn clean install
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t edusoares/discapp .
      - name: Publish image do docker hub
        run: docker push edusoares/discapp:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull edusoares/discapp:latest
      - name: Delete old container
        run: sudo docker rm -f discapp-container || true
      - name: Run docker container
        run: |
          sudo docker run -d -p 8080:8080 --name discapp-container \
            -e DB_URL=${{secrets.DB_URL}} \
            -e DB_USER=postgres \
            -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
            -e JWT_SECRET=${{secrets.JWT_SECRET}} \
            -e SPRING_PROFILES_ACTIVE=prod \
            edusoares/discapp